schema_version: 1

context:
  version: "0.15.4"

package:
  name: cue
  version: ${{ version }}

source:
  url: https://github.com/cue-lang/cue/archive/v${{ version }}.tar.gz
  sha256: 504712c95d8df3b8b4fbb207aed2a3fea49dbdcc5dcfa873a64ca00801d5ef73

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - cue --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: The home of the CUE language! Validate and define text-based and dynamic configuration
  homepage: https://github.com/cue-lang/cue
  repository: https://github.com/cue-lang/cue

extra:
  recipe-maintainers:
    - danielnachun
